version: '3.8'

services:

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "3001:3001"
    env_file:
      - ./user-service/.env
    depends_on:
      user-db:
        condition: service_started
      redis:
        condition: service_started
      message-service:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  message-service:
    build:
      context: ./message-service
    container_name: message-service
    ports:
      - "3002:3002"
    env_file:
      - ./message-service/.env

  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    container_name: user-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ecommerce-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "3003:3003"
    env_file:
      - ./notification-service/.env
    depends_on:
      message-service:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      
  product-db:
    image: postgres:15
    container_name: product-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product_db
    ports:
      - "5434:5432"
    volumes:
      - product_postgres_data:/var/lib/postgresql/data
  
  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "3004:3004"
    depends_on:
      - product-db
    env_file:
      - ./product-service/.env


  cart-service:
    build:
      context: ./cart-service
    container_name: cart-service
    ports:
      - "3005:3005"
    env_file:
      - ./cart-service/.env
    depends_on:
      - cart-db
      - product-service
  cart-db:
    image: postgres:15
    container_name: cart-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cart_db
    ports:
      - "5435:5432"
    volumes:
      - cart_postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  product_postgres_data:
  cart_postgres_data: